"""
Response schemas for the POST /chat endpoint.

The structured response shape is designed to be easily testable with Promptfoo.
Every field has a clear purpose and is observable without reading source code.
"""
from pydantic import BaseModel, Field
from typing import List, Optional


class Citation(BaseModel):
    """
    A reference to a specific record retrieved from a knowledge source.

    Citations prove that the answer is grounded in real data, not hallucinated.
    """

    source: str = Field(
        ...,
        description="Which specialist retrieved this record.",
        examples=["jira", "confluence", "figma", "basic"],
    )
    id: str = Field(
        ...,
        description="The unique identifier of the source record.",
        examples=["PF-104", "CF-005", "FG-006", "BK-001"],
    )
    title: str = Field(
        ...,
        description="Human-readable title of the source record.",
        examples=["Payment confirmation button unresponsive on iOS"],
    )


class RouteInfo(BaseModel):
    """
    Routing metadata — shows exactly how the request was processed.

    This is the most important field for evaluation and debugging:
    it exposes the guard decision, which specialists were called,
    and what the orchestrator decided.
    """

    guard_status: str = Field(
        ...,
        description="Result of the guard check.",
        examples=["allowed", "blocked", "flagged"],
    )
    guard_reason: Optional[str] = Field(
        default=None,
        description="Reason for blocking or flagging. Null if allowed.",
        examples=["prompt_injection", "message_too_long", "harmful_content"],
    )
    selected_specialists: List[str] = Field(
        default_factory=list,
        description="Which specialist agents were invoked.",
        examples=[["jira"], ["jira", "confluence"], []],
    )
    orchestrator_decision: Optional[str] = Field(
        default=None,
        description="Named routing decision from the orchestrator.",
        examples=[
            "jira_blocker_query",
            "cross_source_comparison",
            "unknown_topic_fallback",
        ],
    )


class DebugInfo(BaseModel):
    """
    Debug trace — a step-by-step log of what happened during request processing.

    Students can use this to understand system behavior without reading code.
    """

    app_specialist_task: Optional[str] = Field(
        default=None,
        description="The task description generated by the orchestrator for the specialists.",
    )
    steps: List[str] = Field(
        default_factory=list,
        description="Ordered list of processing steps taken.",
        examples=[
            [
                "Guard check: allowed",
                "Orchestrator decision: jira_blocker_query",
                "Routing to specialists: jira",
                "Jira specialist: 3 result(s) retrieved",
                "Answer synthesized",
                "Response assembled with 3 citation(s)",
            ]
        ],
    )


class ChatResponse(BaseModel):
    """
    Structured response from the PayFlow GenAI assistant.

    Shape is consistent for ALL requests — allowed, blocked, and error cases.
    This consistency is what makes the API reliably testable with Promptfoo.
    """

    answer: str = Field(
        ...,
        description="The grounded natural language answer, or a safe refusal message.",
    )
    route: RouteInfo = Field(
        ...,
        description="Routing metadata including guard status and specialist selection.",
    )
    citations: List[Citation] = Field(
        default_factory=list,
        description="Source records that grounded the answer. Empty for blocked/no-data responses.",
    )
    debug: DebugInfo = Field(
        ...,
        description="Step-by-step processing trace for inspection and debugging.",
    )
